"""Add apollo_id and required class methods to Lead model

Revision ID: 014071afb061
Revises: ccd76972e9d7
Create Date: 2025-11-23 09:47:02.452070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014071afb061'
down_revision = 'ccd76972e9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apollo_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['apollo_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apollo_id')

    # ### end Alembic commands ###
