"""Added two columns trial_rounds_used and is_paid in the user table

Revision ID: 23a490f5b8c5
Revises: 4bd5ec276d98
Create Date: 2026-01-11 14:10:35.063748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a490f5b8c5'
down_revision = '4bd5ec276d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_rounds_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_paid')
        batch_op.drop_column('trial_rounds_used')

    # ### end Alembic commands ###
