"""remove unique email constraint

Revision ID: 43ea96051a9d
Revises: f36f44591ec1
Create Date: 2026-01-11 18:21:42.566160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ea96051a9d'
down_revision = 'f36f44591ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('leads_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('leads_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
