"""Added a column session_id in lead table

Revision ID: e5d054834aee
Revises: 43ea96051a9d
Create Date: 2026-01-11 23:01:56.122041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d054834aee'
down_revision = '43ea96051a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
